language: csharp
solution: RoutinesLibrary.sln
install:
  - nuget restore RoutinesLibrary.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RoutinesLibrary.sln
  - mono ./testrunner/xunit.runner.console*/tools/xunit.console.exe ./test/RoutinesLibrary.Tests/bin/Release/RoutinesLibrary.Tests.dll
